version: '3.7'

services:
  postgres-db:
    image: postgres:17.2-alpine
    # restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=todo_list_app

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "#PgAdmin123!#"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
